### ISSUE TITLE
Quotes in identifiers being interpreted as string delimiters

### ISSUE THREAD

**Issue by GoNZooo** [reasonml-editor/reason-mode#8]
When using reason-mode instead of the previously supplied emacs integration I noticed that if I use quotes in identifiers (as is typical in inner function definitions in order to not name them `..._inner`, reason-mode will interpret them as being string delimiters and thus highlight the entire rest of the buffer as a string.

I'm currently running this through emacs and modified the layer that  @fredyr made to fetch the github repo in `packages.el`.

Is this an issue that is localized only to my specific setup or is there in fact something in the font lock code that could be modified to fix this?

**Comment by fredyr** [comment]
I have also noticed this, but haven't had time to prepare any PRs.
It is due to ' being parsed as string, but iiuc only " should be?

Anyways, this line is the culprit, and by removing it, I have at least not seen any trouble with the code I'm working on.

https://github.com/arichiardi/reason-mode/blob/master/reason-mode.el#L56

**Comment by GoNZooo** [comment]
Yes, though I'm curious if it will affect character literals, being that's what it's supposed to be. Like you, I'll change this and see if there are any new inconsistencies caused by it.

Edit:

I've now checked and the change does make it so that character literals are not picked up as such. It's either something that would have to be remedied separately or a tradeoff to be made in order to have quotes in identifiers be correctly parsed.
